# Generated by Django 4.1.2 on 2022-10-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siimapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritepost',
            name='user_like',
        ),
    ]
