# Generated by Django 4.1.2 on 2022-10-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siimapp', '0005_likepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePost',
        ),
    ]
